### ISSUE TITLE
Error DKIM keys script in Azure Automation Runbook

### ISSUE THREAD

**Issue by guidovanbrakel** [vand3rlinden/AzureAutomation#1]
Hello,

The DKIM script fails in Azure Automation with the following error @vand3rlinden 
`Get-DkimSigningConfig: Line | 5 | $Domains = (Get-DkimSigningConfig | Where-Object {$_.Enabled -eq 'Tru … | ~~~~~~~~~~~~~~~~~~~~~ | The term 'Get-DkimSigningConfig' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
Do you have any idea how to fix it? I have created a Powershell 7.2 runbook and imported the ExchangeOnlineManagement and the other modules as specified from the PowerShell galltery

**Comment by vand3rlinden** [comment]
Does your automation account have an active Exchange Online Administrator role assigned, as outlined in step 6? Additionally, have you completed the other account permissions configuration steps? See: [Setting up an Automation Account with the necessary permissions](https://github.com/vand3rlinden/MDO-Azure-Automation?tab=readme-ov-file#setting-up-an-automation-account-with-the-necessary-permissions)

**Comment by guidovanbrakel** [comment]
> Does your automation account have an active Exchange Online Administrator role assigned, as outlined in step 6? Additionally, have you completed the other account permissions configuration steps? See: [Setting up an Automation Account with the necessary permissions](https://github.com/vand3rlinden/MDO-Azure-Automation?tab=readme-ov-file#setting-up-an-automation-account-with-the-necessary-permissions)

Yes, I did those steps

**Comment by vand3rlinden** [comment]
That’s strange—I am not experiencing any issues with it. 

Did you update the MOERA domain in `C-ROTATE-DKIM-KEYS.ps1` to match the MOERA domain of your tenant?

To troubleshoot, please first ensure that your connection to Exchange Online is working in Azure Automation by testing the `Connect-ExchangeOnline` cmdlet in a new runbook:
`Connect-ExchangeOnline -ManagedIdentity -Organization yourorg.onmicrosoft.com`

**Comment by vand3rlinden** [comment]
After troubleshooting, I found the solution to only connect to Exchange Online through Azure Automation.

I set up a new configuration following the steps outlined in the readme markdown file of this repository. You should have encountered the initial error:
`ERROR: Unable to find type [Microsoft.Exchange.Management.RestApiClient.ExchangeEnvironment]`.

The issue came from the PowerShell Gallery in Azure Automation installing ExchangeOnlineManagement 3.7.0, which is not currently supported. You need to downgrade to version 3.5.0, and it should resolve the problem—I’ve just tested it successfully myself.

To deploy version 3.5.0 to your Azure Automation Account:
	1.	Visit https://www.powershellgallery.com/packages/ExchangeOnlineManagement/3.5.0
	2.	Choose Deploy to Azure Automation.
	3.	Note that it will be deployed in PowerShell runtime 5.1, so you’ll also need to create a new run book with the same runtime version.

I don't know what changed after ExchangeOnlineManagement  3.5.0, but the problem has been known since July 2024: https://learn.microsoft.com/en-us/answers/questions/1840897/connect-exchangeonline-in-azure-automation-account
